add bd classes
LozovskiM/Cinema-system pull request #2
Opened 2020-04-30 12:57 UTC by LozovskiM

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart requested changes
Do you really need all the files in this commit?

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/Cinema.cs
> +namespace Cinema_system.Models
Use CamelCase in namespaces. Also preferably stick to using [Organization].[Product].[Namespace].[SubNameSpace].[SubSubNamespace].[...] pattern

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/Cinema.cs
> +        public int NumOfHalls { get; set; }
Prefer to use full words in names, e.g. NumberOfHalls

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/CinemaDBContext.cs
> +                optionsBuilder.UseSqlServer("Data Source=LAPTOP-HTQV3HQS\\MSSQLSERVER01;Initial Catalog=CinemaDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False
Move connection string to appsettings.json. Use standard configuration tools to access it on application startup.

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/CinemaDBContext.cs
> +                    .HasColumnName("ID")
Why have different column name in database?

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/CinemaDBContext.cs
> +                entity.Property(e => e.CinemaId).HasColumnName("CinemaID");
Start every method call from new line when using fluent syntax.

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/CinemaDBContext.cs
> +                    .OnDelete(DeleteBehavior.ClientSetNull)
Why using this exact strategy? Are you going to have halls without cinemas? What is overall record deletion strategy for your application?

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/Cinema.cs
> +        public int NumOfHalls { get; set; }
What is the purpose of this field?

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/Cinema.cs
> +        public int NumOfSeats { get; set; }
What is the purpose of this field?

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/Hall.cs
> +        public int NumOfSeats { get; set; }
What is the purpose of this field?

2020-05-04 09:44 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/Movie.cs
> +        public DateTime RealiseDate { get; set; }
Did you mean "ReleaseDate"?

2020-05-06 19:29 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/CinemaDBContext.cs
> +                    .HasColumnName("ID")
It's better to use "Id" in database instead. Also do you need to call HasColumnName now when names are the same?

2020-05-12 08:13 UTC, andrei-kruhliakou-itechart requested changes
Please add .vs folder in .gitignore, all those files should not be uploaded to git repo.

2020-05-12 08:13 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/Cinema.cs
> +        public virtual ICollection<Hall> Hall { get; set; }
Collection name should be in plural form, e.g. "Halls"

2020-05-12 08:13 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/CinemaDBContext.cs
> +        public virtual DbSet<Cinema> Cinema { get; set; }
Collection names should be in plural form, e.g. "Cinemas"

2020-05-12 08:13 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/SeanceSeat.cs
> +        public double Price { get; set; }
Do not use types with floating point for money, use decimal instead.

2020-05-12 08:13 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/SeanceSeat.cs
> +        public bool Available { get; set; }
Boolean properties should in general use Is or Has prefix, e.g "IsAvailable", "HasEmptySeats", etc

2020-05-12 08:13 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/Seat.cs
> +        public string TypeOfSeat { get; set; }
Why use string for this property? If you have fixed list of possible values it's much better to use Enum or lookup table.

2020-05-12 08:13 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/Seat.cs
> +        public virtual ICollection<Order> Order { get; set; }
What is the purpose of this field? You can use one way navigation properties, e.g. Order having collection of Seats makes sense, but Seat having collection of Orders most probably not.

2020-05-12 14:45 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/Seat.cs
> +        public enum SeatType
Can you please move it outside of a class?

2020-05-12 14:45 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/SeanceSeat.cs
> +        public double Price { get; set; }
How are you going to handle prices with fractions, like 2.50?

2020-05-12 14:45 UTC, andrei-kruhliakou-itechart commented on Cinema system/Cinema system/Models/CinemaDBContext.cs
> +        public virtual DbSet<Cinema> Cinema { get; set; }
This is still not fixed

2020-05-12 14:48 UTC, andrei-kruhliakou-itechart requested changes
I can still see files from .vs folder in the commit, can you please delete them?

2020-05-12 16:49 UTC, LozovskiM reviewed
Sorry, forgot to save gitignore to exclude .vs folders. I'll do it in the next commit.

2020-05-12 17:02 UTC, andrei-kruhliakou-itechart approved these changes

2020-05-12 17:03 UTC, merged